# Generated by Django 4.0.4 on 2022-11-06 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categoria',
        ),
    ]
