# Generated by Django 4.0.4 on 2022-11-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0002_rename_category_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url_clean', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listelement.categoria')),
            ],
        ),
        migrations.RenameModel(
            old_name='Type',
            new_name='Tipo',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.AddField(
            model_name='producto',
            name='Tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listelement.tipo'),
        ),
    ]
