# Generated by Django 4.0.4 on 2022-11-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0003_producto_rename_type_tipo_delete_element_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='url_clean',
            new_name='nombre_prod',
        ),
    ]
