# Generated by Django 4.0.4 on 2022-11-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0005_rename_nombre_prod_producto_nombre_prodcuto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
