# Generated by Django 4.0.4 on 2022-11-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0006_remove_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='title',
            new_name='nombre_categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre_prodcuto',
            new_name='id_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='title',
            new_name='nombre_producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Tipo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='id_categoria',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_producto',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Tipo',
        ),
    ]
