# Generated by Django 4.0.4 on 2022-11-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0007_rename_title_categoria_nombre_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_producto',
        ),
    ]
