# Generated by Django 4.0.4 on 2022-11-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0008_remove_producto_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
