# Generated by Django 4.0.4 on 2022-11-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0009_producto_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
