# Generated by Django 4.0.4 on 2022-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0010_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
