# Generated by Django 4.0.4 on 2022-11-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0011_alter_producto_precio_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='id_categoria',
        ),
    ]
