# Generated by Django 4.0.4 on 2022-11-13 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0012_remove_categoria_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='url_clean',
        ),
    ]
