# Generated by Django 4.0.4 on 2022-11-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0013_remove_categoria_url_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='images/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listelement.producto')),
            ],
        ),
    ]
