# Generated by Django 4.0.4 on 2022-11-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0014_productoimagenes'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.DeleteModel(
            name='ProductoImagenes',
        ),
    ]
