# Generated by Django 4.0.4 on 2022-11-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0016_alter_producto_precio_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='url_clean',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='url_clean',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
