# Generated by Django 4.0.4 on 2022-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0017_categoria_url_clean_producto_url_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
